name: Terraform GCP Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted

    env:
      TF_VERSION: "1.5.0"
      GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: "us-central1"
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure GCP credentials
        run: |
          echo "${GCP_SA_KEY}" > $HOME/gcp-key.json

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Plan
        run: terraform -chdir=terraform plan               -var="project_id=${GCP_PROJECT}"               -var="region=${GCP_REGION}"               -var="credentials_file=$HOME/gcp-key.json"

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve               -var="project_id=${GCP_PROJECT}"               -var="region=${GCP_REGION}"               -var="credentials_file=$HOME/gcp-key.json"
