name: Terraform GCP Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted

    env:
      TF_VERSION: "1.5.0"
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      GCP_SA_KEY: ${{ secrets.GCP_CREDENTIALS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Debug secrets (optional)
        run: |
          echo "GCP_PROJECT=${GCP_PROJECT}"
          echo "GCP_REGION=${GCP_REGION}"
          echo "GCP_SA_KEY length=${#GCP_SA_KEY}"

      - name: Configure GCP credentials
        run: |
          printf "%s" "${GCP_SA_KEY}" > $HOME/gcp-key.json

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Plan
        run: terraform -chdir=terraform plan \
              -var="project_id=${GCP_PROJECT}" \
              -var="region=${GCP_REGION}" \
              -var="credentials_file=$HOME/gcp-key.json"

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve \
              -var="project_id=${GCP_PROJECT}" \
              -var="region=${GCP_REGION}" \
              -var="credentials_file=$HOME/gcp-key.json"
